name: Check & fix styling

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: PHP CS Fixer
      uses: StephaneBour/actions-php-cs-fixer@1.0

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Fixed styling
