name: Check & fix styling

on: [push]

jobs:
  style:
    runs-on: ubuntu-latest

    steps:
    - name: PHP CS Fixer
      uses: StephaneBour/actions-php-cs-fixer@1.0
      with:
          dir: './' 
